name: Flask CI pipeline

on:
  push:
    paths:
      - 'flask/**'

jobs:
  build:

  runs-on: ubuntu-latest

  steps:
    - 
      uses: actions/checkout@v3
    - 
      name: Set up python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.6"
    - 
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask
        pip install -r requirements.txt
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: jnavarro447/helloworld-flask:latest
