
name: Go CI pipeline

on:
  push:
    paths:
      - 'golang/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v3
    - 
      name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - 
      name: Build
      run: go build ./golang/main.go

    #-
    #  name: Test
    #  run: go test -v ./...

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: golang/
          push: true
          tags: jnavarro447/helloworld-go:latest
